export default {
    INITIATE_SIGN_IN: 'INITIATE_SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    INITIATE_SIGN_UP: 'INITIATE_SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    GET_JWT_TOKEN: 'GET_JWT_TOKEN',
    GET_JWT_TOKEN_SUCCESSFUL: 'GET_JWT_TOKEN_SUCCESSFUL',
    GET_JWT_TOKEN_FAILURE:'GET_JWT_TOKEN_FAILURE',
    INITIATE_SEARCH_CHATHEADS:'INITIATE_SEARCH_CHATHEADS',
    SEARCH_CHATHEADS_SUCCESS:' SEARCH_CHATHEADS_SUCCESS',
    SEARCH_CHATHEADS_FAILURE:' SEARCH_CHATHEADS_FAILURE'
}